[package]
name = "mev-inspect"
version = "0.1.0"
authors = ["Georgios Konstantopoulos <me@gakonst.com>"]
edition = "2018"

[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", branch = "master", features = ["abigen"] }
serde_json = "1.0.61"
once_cell = "1.5.2"
itertools = "0.10.0"
anyhow = "1.0.37"

# cached provider
thiserror = "1.0.23"
async-trait = "0.1.42"
serde = "1.0.118"

# postgres connection
tokio = { version = "1.0.1", features = ["macros", "rt-multi-thread"] }
tokio-postgres = "0.7.0"
rust_decimal = { version = "1.9.0", features = ["db-postgres", "db-tokio-postgres"] }
gumdrop = "0.8.0"
futures = "0.3.8"
hex = "0.4.2"

[features]
postgres-tests = []

[patch.crates-io]
rust_decimal = { git = "https://github.com/paupino/rust-decimal/", branch = "master" }
reqwest = { git = "https://github.com/seanmonstar/reqwest", branch = "master" }
tokio-tungstenite = { git = "https://github.com/dnaka91/tokio-tungstenite", branch = "tokio-1.0" }

